spring:

  docker:
    compose:
      enabled: true
      lifecycle-management: start_only
      file: src/main/docker/compose.yaml

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: public
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: db/changelog/master.yaml
server:
  port: 8888

stripe:
  api:
    key: sk_test_51QtoIwDMtDp6WnpOtVlFQyURm9JX4bJrH788iNzRSovvNUUm1LQ1OLqPUrG92laVOJNi69f2HBX9XK8k3FlM3hPr00n8vHq4zF
